//! Per-install keyed hash for `OpenCode` prompt reconciliation.
//!
//! Linking a command to its imported prompt across possibly-different
//! per-directory redaction policies needs a stable fingerprint of the
//! prompt's original text. A bare, unkeyed hash of that text would let
//! anyone who can read the local database or prompt cache offline
//! dictionary-guess a redacted secret by hashing candidates and comparing
//! -- exactly the class of low-entropy secret redaction exists to protect.
//! An HMAC keyed with a random, owner-only-readable per-install secret
//! closes that: guessing a match also requires compromising this key file.
use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// HMAC-SHA256 of `text` under this install's reconciliation key, hex
/// encoded. Returns `None` (not an error) if the key can't be loaded or
/// generated -- callers already treat a missing hash as "fall back to
/// exact-text match", the behavior before this fingerprint existed.
pub fn keyed_text_hash(text: &str) -> Option<String> {
    let key = reconcile_key().ok()?;
    let mut mac = <HmacSha256 as Mac>::new_from_slice(&key).ok()?;
    mac.update(text.as_bytes());
    Some(format!("hmac-sha256:{:x}", mac.finalize().into_bytes()))
}

/// Load this install's reconciliation key, generating and persisting a
/// random one on first use.
///
/// The candidate key is written to a temp file in the same directory with
/// owner-only permissions applied *before* it's ever linked into place,
/// then hard-linked (not renamed) into `reconcile.key`. A hard link only
/// ever succeeds once for a given destination, so unlike creating the
/// destination empty and writing its content afterward (a window where a
/// concurrent reader sees a 0-byte file and silently gets no fingerprint)
/// or persisting via rename (which would silently overwrite a concurrent
/// winner's already-in-use key), a concurrent reader of `reconcile.key`
/// either doesn't find it yet or finds it fully written and correctly
/// permissioned -- never partial, never wrongly-permissioned, never
/// clobbered. Whichever process's link wins keeps its own generated bytes;
/// every other process discards its own and reads the winner's back
/// instead, so every caller of `keyed_text_hash` ends up hashing under the
/// same key without needing a lock or a retry loop.
fn reconcile_key() -> Result<[u8; 32], Box<dyn std::error::Error>> {
    let dirs = super::project_dirs().ok_or("Could not determine data directory")?;
    reconcile_key_at(dirs.data_dir())
}

/// Same as [`reconcile_key`], parameterized on the data directory so tests
/// can race it against a directory dedicated to just one test, rather than
/// the whole test binary's shared `project_dirs()` sandbox.
fn reconcile_key_at(data_dir: &std::path::Path) -> Result<[u8; 32], Box<dyn std::error::Error>> {
    let key_path = data_dir.join("reconcile.key");
    if let Some(key) = read_key(&key_path) {
        return Ok(key);
    }
    std::fs::create_dir_all(data_dir)?;

    let mut key = [0u8; 32];
    key[..16].copy_from_slice(uuid::Uuid::new_v4().as_bytes());
    key[16..].copy_from_slice(uuid::Uuid::new_v4().as_bytes());

    let temp = tempfile::NamedTempFile::new_in(data_dir)?;
    std::fs::write(temp.path(), key)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(temp.path(), std::fs::Permissions::from_mode(0o600))?;
    }
    match std::fs::hard_link(temp.path(), &key_path) {
        Ok(()) => Ok(key),
        // Another process linked its own candidate key first; use its key
        // instead of the one just generated here, so both sides of a
        // reconciliation always end up hashing under the same key.
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
            read_key(&key_path).ok_or_else(|| e.into())
        }
        Err(e) => Err(e.into()),
    }
}

fn read_key(path: &std::path::Path) -> Option<[u8; 32]> {
    let bytes = std::fs::read(path).ok()?;
    <[u8; 32]>::try_from(bytes).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A synchronized burst of first-use calls against a fresh, dedicated
    /// directory. A prior create-then-write implementation (create the
    /// destination file empty, write its 32 bytes afterward, chmod last)
    /// reliably made a large fraction of these calls observe an empty or
    /// wrongly-permissioned file mid-write and return no key at all —
    /// reproduced 5 of 8 runs, up to 48 of 64 threads, when this test was
    /// written against that implementation. The barrier packs every
    /// thread's first attempt into as small a window as possible; real
    /// `suv` subprocesses can't be raced this tightly (see
    /// `opencode_concurrent_first_use_key_creation_is_race_safe` in
    /// `tests/opencode_hooks.rs` for the same property end-to-end).
    #[test]
    #[allow(clippy::needless_collect)] // must spawn every thread before joining any
    fn concurrent_first_use_never_misses_a_key_or_disagrees_on_it() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().to_path_buf();
        let threads = 64;
        let barrier = std::sync::Arc::new(std::sync::Barrier::new(threads));
        let results: Vec<Result<[u8; 32], String>> = std::thread::scope(|scope| {
            let handles: Vec<_> = (0..threads)
                .map(|_| {
                    let path = &path;
                    let barrier = std::sync::Arc::clone(&barrier);
                    scope.spawn(move || {
                        barrier.wait();
                        reconcile_key_at(path).map_err(|e| e.to_string())
                    })
                })
                .collect();
            handles.into_iter().map(|h| h.join().unwrap()).collect()
        });

        let failures: Vec<&String> = results.iter().filter_map(|r| r.as_ref().err()).collect();
        assert!(failures.is_empty(), "some threads got no key: {failures:?}");
        let distinct: std::collections::HashSet<_> =
            results.iter().filter_map(|r| r.as_ref().ok()).collect();
        assert_eq!(
            distinct.len(),
            1,
            "threads disagreed on the key: {} distinct values across {threads} threads",
            distinct.len()
        );
    }

    #[test]
    fn keyed_text_hash_is_deterministic_and_persists_the_key_across_calls() {
        let a = keyed_text_hash("hello").unwrap();
        let b = keyed_text_hash("hello").unwrap();
        assert_eq!(a, b);
        assert_ne!(a, keyed_text_hash("different text").unwrap());
    }

    #[test]
    fn keyed_text_hash_is_not_a_bare_unkeyed_hash() {
        use sha2::Digest;
        let unkeyed = format!("sha256:{:x}", Sha256::digest(b"hello"));
        assert_ne!(keyed_text_hash("hello").unwrap(), unkeyed);
    }
}
