//! Shared launchers for installed agent hooks. Event input is only passed on stdin.
use std::path::{Path, PathBuf};

pub fn script(binary: &str, target: &str, integration: &str) -> String {
    let escaped = super::shell_escape(binary);
    let metadata = serde_json::json!({"binary": binary, "target": target});
    format!(
        "#!/bin/sh\n\
         # Suvadu agent hook — generated by suv init {integration}\n\
         # suvadu-hook: {metadata}\n\
         _suvadu_bin={escaped}\n\
         if [ ! -f \"$_suvadu_bin\" ] || [ ! -x \"$_suvadu_bin\" ]; then\n\
           _suvadu_bin=$(command -v suv 2>/dev/null)\n\
         fi\n\
         if [ -z \"$_suvadu_bin\" ] || [ ! -x \"$_suvadu_bin\" ]; then\n\
           echo 'suvadu: binary not found; reinstall Suvadu and run suv init {integration}' >&2\n\
           exit 1\n\
         fi\n\
         exec \"$_suvadu_bin\" {target}\n"
    )
}

pub fn executable(path: &Path) -> bool {
    let Ok(metadata) = std::fs::metadata(path) else {
        return false;
    };
    if !metadata.is_file() {
        return false;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        metadata.permissions().mode() & 0o111 != 0
    }
    #[cfg(not(unix))]
    {
        true
    }
}

fn path_binary() -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|path| {
        std::env::split_paths(&path)
            .map(|dir| dir.join("suv"))
            .find(|p| executable(p))
    })
}

/// Inspect rather than execute scripts: doctor must not run arbitrary hook code.
pub fn inspect(path: &Path) -> Result<(), String> {
    let contents = std::fs::read_to_string(path).map_err(|_| "cannot read script".to_string())?;
    if !executable(path) {
        return Err("script is not executable".into());
    }
    if let Some(metadata) = contents
        .lines()
        .find_map(|line| line.strip_prefix("# suvadu-hook: "))
    {
        let value: serde_json::Value =
            serde_json::from_str(metadata).map_err(|_| "invalid hook metadata".to_string())?;
        let binary = value["binary"].as_str().ok_or("missing binary path")?;
        if executable(Path::new(binary)) || path_binary().is_some() {
            return Ok(());
        }
        return Err("saved binary is missing and suv is not on PATH".into());
    }
    // Older generated scripts used a shell-escaped, single-quoted absolute path.
    if let Some(binary) = contents.lines().find_map(|line| {
        line.strip_prefix("exec '")
            .and_then(|rest| rest.split_once("' hook-"))
            .map(|(path, _)| path.replace("'\\''", "'"))
    }) {
        if executable(Path::new(&binary)) {
            return Ok(());
        }
        return Err(format!(
            "saved binary is missing or not executable: {binary}"
        ));
    }
    Err("unrecognized hook script; regenerate to verify its binary".into())
}
